---
- name: "Playbook to test the inventory_hostname and ansible_hostname"
  hosts: all
  gather_facts: True
  tasks:

   - name: inventory_hostname
     debug:
       msg: "{{ inventory_hostname }}"

   - name: group_names
     debug:
       msg: "{{ group_names }}"

   - name: ansible_hostname
     debug:
       msg: "{{ ansible_hostname }}"

   - name: ansible_user
     debug:
       msg: "{{ ansible_user }}"

   - name: playbook_dir
     debug:
       msg: "{{ playbook_dir }}"
