---
- name: Change hostname to mirror (for mirror ec2 instance)
  hostname:
    name: mirror

- name: copy over mirror_setup.sh file
  copy:
    src: "{{ playbook_dir }}/mirror/mirror_setup.sh"
    dest: "/home/{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0770"

- name: copy over multiply.nft file
  copy:
    src: "{{ playbook_dir }}/mirror/multiply.nft"
    dest: "/home/{{ ansible_user }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0660"

- name: Setup mirror with mirror_setup.sh and multiply.nft
  shell: |
    sudo "/home/{{ ansible_user}}/mirror_setup.sh"
    sudo nft flush ruleset
    sudo nft --file "/home/{{ ansible_user}}/multiply.nft"
