---
- include_vars: "{{ playbook_dir}}/tf_ansible_vars/ansible_vars.yml"

- name: copy over 90-dns-none.conf file
  copy:
    src: 90-dns-none.conf
    dest: "/etc/NetworkManager/conf.d/90-dns-none.conf"
    owner: root
    group: root
    mode: "0644"

- name: reload NetworkManager
  systemd:
    name: NetworkManager
    enabled: True
    state: reloaded

- name: copy over resolv.conf file
  template:
    src: resolv.conf.j2
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: "0644"

- name: reload NetworkManager
  systemd:
    name: NetworkManager
    enabled: True
    state: reloaded


- name: Get the instance identity document
  uri:
    url: "http://169.254.169.254/latest/dynamic/instance-identity/document"
    return_content: true
  register: identity_doc

- set_fact:
    instance_metadata: "{{ identity_doc.json }}"

- name: Change MOTD banner
  template:
    src: motd.j2
    dest: /etc/motd
  register: motd_file

- name: Restart ssh when updated
  service:
    name: sshd
    state: restarted
  when: motd_file.changed
