---
- name: Install syslog-ng package
  dnf:
    state: latest
    name:
      - syslog-ng

- name: Enable syslog-ng
  systemd:
    name: syslog-ng
    enabled: True
    state: restarted

- name: Disable rsyslog
  systemd:
    name: rsyslog
    enabled: False
    state: stopped
