---

- name: Ensure git is installed.
  dnf:
    name: "git"
    state: present

- name: Clone syslog-generator-1 from repository
  git:
    repo: "https://github.com/richlamdev/syslog-generator-1.git"
    dest: "/home/{{ local_username }}/git/syslog-generator-1/"
    update: no
